# Generated by Django 5.1.2 on 2024-11-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
